tour_londres_dashboard:
    resource: "@TourLondresDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

tour_londres_tour:
    resource: "@TourLondresTourBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

general:
    resource: "@GeneralBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

